### ISSUE TITLE
US6 - Backend implementation (CREATE)

### ISSUE THREAD

**Issue by uwebury** [uwebury/trip-trove#10]
## Value proposition
As a developer
I want to to handle the data in the database
In order to store and fetch the data permanently and more securely

## Description
![US6 - Backend implementation CREATE](https://github.com/uwebury/trip-trove/assets/149960642/600ad1d4-d151-46d9-85a1-2bf2fdd60453)

## Tasks
- [ ] Create handleSubmit(event) function (POST method)
- [ ] Implement handleSubmit function to Save Button (onSubmit = {handleSubmit})

**Comment by JuliaSchw** [comment]
looks good :) it's a developer story. but i think thats okay :)

**Comment by CJAkkuec** [comment]
> looks good :) it's a developer story. but i think thats okay :)
It is, but I let them know that they don't need to break their chronology of user stories to include DS1, DS2, etc.

The tasks are a little bare bones, but seeing as how it's essentially just plugging the cables in differently, I don't mind.
